spring:
  config:
    import:
      - classpath:mysql.yaml
      - classpath:open-ai.yaml
      - classpath:google.yaml
      - classpath:jwt.yaml
      - classpath:domain.yaml

  application:
    name: chat-diary

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
