services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql  # Use named volume instead
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
volumes:
  mysql_data:
