spring:
  application:
    name: chat-diary

  datasource:
    url: jdbc:mysql://${MYSQL_URL}:${MYSQL_PORT}/chat_diary
    username: root
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

security:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    expiration: ${JWT_EXPIRE}
    rsa-private-key: classpath:certs/private.pem
    rsa-public-key: classpath:certs/public.pem

oauth:
  google:
    clientId: ${GOOGLE_CLIENT_ID}
    clientSecret: ${GOOGLE_CLIENT_SECRET}

domain:
  frontend: ${FRONTEND_URL}
